name: color_shift
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.0.1
  a_star:
    git: 
      url: https://github.com/Levi-Lesches/dart-a-star.git
      ref: api-refactor

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: assets/icon.jpg
  android: "launcher_icon"
  adaptive_icon_foreground: assets/icon.jpg
  adaptive_icon_background: "#ffffff"
